Add runbook
isfandiyoro5/HotelMS pull request #12
Opened 2023-04-28 08:01 UTC by mrIminjonov

README.md qoshdim

2023-04-28 08:17 UTC, JmlKhon requested changes

2023-04-28 08:17 UTC, JmlKhon commented on README.md
> +# Dasturni ishga tushirish uchun kompyuterga sozlash;
kampyuterni boladi

2023-04-28 08:17 UTC, JmlKhon commented on README.md
> +1. Projectni **`Visual  Studio`** da ochasiz;
1. shart kerak emas. dasturni faqat visual studio da ishlatsa bo;adi degan ma'no ketgan. Aslida buni boshqa IDE larda ham ishlatsa boladi. EX: VS Code, Rider etc

2023-04-28 08:17 UTC, JmlKhon commented on README.md
> +2. *`appsettings.json`* ga kirasiz;
2. Appsettingdagi hammasozlanmalarni bittada yozasiz

2023-04-28 08:19 UTC, mrIminjonov commented on README.md
> +# Dasturni ishga tushirish uchun kompyuterga sozlash;
hop ozgartitib qoyaman

2023-04-28 08:20 UTC, mrIminjonov commented on README.md
> +1. Projectni **`Visual  Studio`** da ochasiz;
hop

2023-04-28 08:20 UTC, mrIminjonov commented on README.md
> +2. *`appsettings.json`* ga kirasiz;
hop

2023-04-28 12:00 UTC, JmlKhon requested changes

2023-04-28 12:00 UTC, JmlKhon commented on README.md
> +1. Dasturni ishga tushirasiz;
ob tashash kerak. appsettingni sozlamasdan ishga tushurib bomaydiku

2023-04-28 16:36 UTC, mrIminjonov commented on README.md
> +1. Dasturni ishga tushirasiz;
ochirvordim

2023-04-28 16:36 UTC, isfandiyoro5 approved these changes, later dismissed

2023-04-29 17:48 UTC, isfandiyoro5 submitted a review, later dismissed

2023-04-29 18:41 UTC, SheraliErkayev submitted a review, later dismissed

2023-04-30 06:33 UTC, isfandiyoro5 approved these changes

2023-05-01 14:50 UTC, JmlKhon approved these changes

2023-05-01 14:52 UTC, merged