Added Services
isfandiyoro5/HotelMS pull request #15
Opened 2023-05-02 18:28 UTC by isfandiyoro5

Added Services, 
async await

2023-05-02 18:36 UTC, mrIminjonov requested changes

2023-05-02 18:36 UTC, mrIminjonov commented on TestHotel/TestHotel.Service/Service/Services/EmployeeService.cs
> +        public EmployeeService(EmployeeRepository employeerepository)
employeerepository ni employeeRepository qibqoy

2023-05-02 18:36 UTC, mrIminjonov commented on TestHotel/TestHotel.Service/Service/Services/EmployeeService.cs
> +            _employeeRepository= employeerepository;
bu yerda ham

2023-05-03 06:37 UTC, isfandiyoro5 commented on TestHotel/TestHotel.Service/Service/Services/EmployeeService.cs
> +        public EmployeeService(EmployeeRepository employeerepository)
done

2023-05-03 06:37 UTC, isfandiyoro5 commented on TestHotel/TestHotel.Service/Service/Services/EmployeeService.cs
> +            _employeeRepository= employeerepository;
Ok

2023-05-04 13:48 UTC, JmlKhon requested changes

2023-05-04 13:48 UTC, JmlKhon commented on TestHotel/TestHotel.Service/Service/IServices/IBillService.cs
> +        Task<int> DeleteBillAsync(Bill bill);
delete Id bo'yicha delete qimassmidi?

2023-05-04 13:48 UTC, JmlKhon commented on TestHotel/TestHotel.Service/Service/IServices/IBillService.cs
> +        Task<int> UpdateBillAsync(Bill bill);
Update ham Id bo'yicha update qimasmidi

2023-05-04 13:48 UTC, JmlKhon commented on TestHotel/TestHotel.Service/Service/Services/BillService.cs
> +            var billExist = await GetBillByIdAsync(bill.InvoiceNumber);
change var name

2023-05-04 13:48 UTC, JmlKhon commented on TestHotel/TestHotel.Service/Service/Services/BillService.cs
> +            if (billExist != null)
change to "is not"

2023-05-04 13:48 UTC, JmlKhon commented on TestHotel/TestHotel.Service/Service/Services/BillService.cs
> +                return 0;
throw new exception with message

2023-05-05 11:17 UTC, isfandiyoro5 commented on TestHotel/TestHotel.Service/Service/IServices/IBillService.cs
> +        Task<int> DeleteBillAsync(Bill bill);
Done

2023-05-05 11:20 UTC, isfandiyoro5 commented on TestHotel/TestHotel.Service/Service/IServices/IBillService.cs
> +        Task<int> UpdateBillAsync(Bill bill);
Done

2023-05-05 11:33 UTC, isfandiyoro5 commented on TestHotel/TestHotel.Service/Service/Services/BillService.cs
> +            var billExist = await GetBillByIdAsync(bill.InvoiceNumber);
Done

2023-05-05 11:33 UTC, isfandiyoro5 commented on TestHotel/TestHotel.Service/Service/Services/BillService.cs
> +            if (billExist != null)
Done

2023-05-05 11:49 UTC, isfandiyoro5 commented on TestHotel/TestHotel.Service/Service/Services/BillService.cs
> +                return 0;
Done

2023-05-07 10:43 UTC, SheraliErkayev approved these changes

2023-05-09 05:20 UTC, MirazamTUT approved these changes

2023-05-09 17:45 UTC, JmlKhon approved these changes

2023-05-10 05:00 UTC, mrIminjonov approved these changes

2023-05-10 05:03 UTC, merged