Updated Exceptions in Repositories
isfandiyoro5/HotelMS pull request #16
Opened 2023-05-04 10:33 UTC by Bekhzod7799

BillRepository ni qarab bering to'gri bo'lsa qolganini keyin tugatib qo'yamiz.

2023-05-04 13:58 UTC, JmlKhon requested changes

2023-05-04 13:58 UTC, JmlKhon commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/BillRepository.cs
> +                _logger.LogError($"Billni databazaga qo'shishda xatolik bor: {ex.Message}");
_logger.LogError("Billni databazaga qo'shishda xatolik bor: {0}",ex.Message);

2023-05-04 13:58 UTC, JmlKhon commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/BillRepository.cs
> +            catch (DbUpdateConcurrencyException ex)
remove it

2023-05-04 13:58 UTC, JmlKhon commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/BillRepository.cs
> +                _logger.LogError($"Billni databazadan o'chirishda xatolik mavjud: {ex.Message}");
add ex.StackTrace

2023-05-04 13:58 UTC, JmlKhon commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/BillRepository.cs
> +                _logger.LogError($"Databazada barcha Billarni olishda xatolik yuz berdi.: {ex.Message}");
fix it

2023-05-05 09:42 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/BillRepository.cs
> +                _logger.LogError($"Billni databazadan o'chirishda xatolik mavjud: {ex.Message}");
done

2023-05-05 09:43 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/BillRepository.cs
> +            catch (DbUpdateConcurrencyException ex)
done

2023-05-05 09:43 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/BillRepository.cs
> +                _logger.LogError($"Databazada barcha Billarni olishda xatolik yuz berdi.: {ex.Message}");
done

2023-05-05 09:43 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/BillRepository.cs
> +                _logger.LogError($"Billni databazaga qo'shishda xatolik bor: {ex.Message}");
done

2023-05-07 06:53 UTC, JmlKhon approved these changes, later dismissed

2023-05-07 09:56 UTC, isfandiyoro5 requested changes

2023-05-07 09:56 UTC, isfandiyoro5 commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/GuestRepository.cs
> +                throw new Exception("An error occurred while executing the SQL query.", ex);
shu joyini tog'irlab qoying  
("SQL so'rovini bajarishda xatolik yuz berdi") ga

2023-05-09 07:04 UTC, MirazamTUT requested changes

2023-05-09 07:04 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/HotelRepository.cs
> +
Id bo'yicha if shartmas Id ni serviceda tekshiramiz

2023-05-09 07:04 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/HotelRepository.cs
> +            }
ArgumentNullException bu ham shart emas 
yoki men adashyapmanmi?

2023-05-09 07:04 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/GuestRepository.cs
> +            }
ArgumentNullException kerak emas chunki qolgan repositorylarda GetById metodlarida ArgumentNullException yo'q

2023-05-09 07:04 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/GuestRepository.cs
> +            }
SqlException ni olib tashlash kerak boshqa GetAll methodlarda bu exception ishlatilmagan

2023-05-09 17:45 UTC, JmlKhon approved these changes

2023-05-09 17:54 UTC, JmlKhon requested changes

2023-05-09 17:54 UTC, JmlKhon commented on TestHotel/TestHotel.DataAccess/Repository/Repositories/HotelRepository.cs
> +                throw;
nimaga throw ni ozi ishlatilgan?

2023-05-13 19:52 UTC, isfandiyoro5 approved these changes

2023-05-14 16:13 UTC, MirazamTUT approved these changes

2023-05-16 14:22 UTC, JmlKhon approved these changes

2023-05-16 14:22 UTC, merged