Edited Program.cs for CRUD
isfandiyoro5/HotelMS pull request #22
Opened 2023-05-23 12:34 UTC by isfandiyoro5

2023-05-23 12:37 UTC, MirazamTUT requested changes

2023-05-23 12:37 UTC, MirazamTUT commented on TestHotel/TestHotel.API/Program.cs
> +builder.Services.AddScoped<IRoomTypeService, RoomTypeService>();
bu registratsiyalani service dagi RegisterServicega yozish kerak

2023-05-23 16:18 UTC, isfandiyoro5 commented on TestHotel/TestHotel.API/Program.cs
> +builder.Services.AddScoped<IRoomTypeService, RoomTypeService>();
Done

2023-05-24 13:52 UTC, MirazamTUT approved these changes

2023-05-26 16:50 UTC, SheraliErkayev approved these changes

2023-05-26 16:51 UTC, merged