Added Test Projects
isfandiyoro5/HotelMS pull request #23
Opened 2023-05-24 13:45 UTC by MirazamTUT

2023-05-30 13:13 UTC, JmlKhan requested changes
Unit.Test

2023-05-30 13:14 UTC, JmlKhan requested changes
DataAccess.Test

2023-05-30 17:57 UTC, isfandiyoro5 approved these changes

2023-05-30 17:58 UTC, mrIminjonov approved these changes

2023-05-31 14:00 UTC, JmlKhan approved these changes

2023-06-01 05:36 UTC, merged