Added Controller
isfandiyoro5/HotelMS pull request #24
Opened 2023-05-26 20:02 UTC by SheraliErkayev

2023-05-27 03:39 UTC, isfandiyoro5 requested changes

2023-05-27 03:39 UTC, isfandiyoro5 commented on TestHotel/TestHotel.API/Controllers/EmployeeController.cs
> +
Line wop ketibdi op tashash kk

2023-05-31 08:08 UTC, isfandiyoro5 requested changes

2023-05-31 08:08 UTC, isfandiyoro5 commented on TestHotel/TestHotel.API/Controllers/BillController.cs
> +        [HttpDelete("Id")]
Sherali aka SHu yerda 'Id' mas INvoiceNumber boladi

2023-05-31 12:58 UTC, SheraliErkayev commented on TestHotel/TestHotel.API/Controllers/BillController.cs
> +        [HttpDelete("Id")]
Togirlandi

2023-05-31 13:58 UTC, JmlKhan approved these changes

2023-06-01 10:33 UTC, isfandiyoro5 approved these changes

2023-06-01 10:33 UTC, merged