Updated models
isfandiyoro5/HotelMS pull request #27
Opened 2023-06-15 04:47 UTC by MirazamTUT

O'zgartirilgan narsalar: 
"RoomType" "Room" modelga qo'shildi,
Relationshiplar to'g'irlandi,
Kerakmas NameSpacelar o'chirildi,
Ortiqcha Packege lar olib tashlandi. 

Hali qo'shilmagan narsalar: 
Bogus.

2023-06-15 10:49 UTC, SheraliErkayev approved these changes, later dismissed

2023-06-15 10:50 UTC, JmlKhan requested changes, later dismissed

2023-06-15 10:50 UTC, JmlKhan commented on TestHotel/TestHotel.DataAccess/Model/Room.cs
> +    public enum Occupency
*Occupancy

2023-06-15 10:52 UTC, JmlKhan commented
> O'zgartirilgan narsalar: "RoomType" "Room" modelga qo'shildi, Relationshiplar to'g'irlandi, Kerakmas NameSpacelar o'chirildi, Ortiqcha Packege lar olib tashlandi.
> 
> Hali qo'shilmagan narsalar: Bogus.

Bogus ni alohida branchda qilish kerak. U boshqa feature ku shuchun

2023-06-15 10:55 UTC, JmlKhan commented
> O'zgartirilgan narsalar: "RoomType" "Room" modelga qo'shildi, Relationshiplar to'g'irlandi, Kerakmas NameSpacelar o'chirildi, Ortiqcha Packege lar olib tashlandi.
> 
> Hali qo'shilmagan narsalar: Bogus.

Swaggerda test qib kordizmi hamma endpointlarni?

2023-06-15 14:33 UTC, isfandiyoro5 approved these changes, later dismissed

2023-06-15 15:20 UTC, isfandiyoro5 submitted a review, later dismissed

2023-06-16 06:07 UTC, Bekhzod7799 approved these changes, later dismissed

2023-06-16 11:44 UTC, isfandiyoro5 submitted a review, later dismissed

2023-06-16 12:17 UTC, isfandiyoro5 submitted a review, later dismissed

2023-06-16 12:18 UTC, SheraliErkayev approved these changes, later dismissed

2023-06-16 12:19 UTC, isfandiyoro5 submitted a review, later dismissed

2023-06-16 12:27 UTC, JmlKhan submitted a review, later dismissed

2023-06-16 12:27 UTC, JmlKhan approved these changes

2023-06-16 12:27 UTC, isfandiyoro5 approved these changes

2023-06-16 12:27 UTC, SheraliErkayev approved these changes

2023-06-16 12:28 UTC, JmlKhan approved these changes

2023-06-16 12:29 UTC, merged