Added Email to project
isfandiyoro5/HotelMS pull request #28
Opened 2023-06-21 18:25 UTC by isfandiyoro5

2023-06-22 11:05 UTC, mrIminjonov requested changes

2023-06-22 11:05 UTC, mrIminjonov commented on TestHotel/EmailService/EmailSender.cs
> +    internal class EmailSender
ochirvor

2023-06-22 11:05 UTC, mrIminjonov commented on TestHotel/EmailService/IEmailSender.cs
> +    {
buniyam

2023-06-22 11:05 UTC, mrIminjonov commented on TestHotel/EmailService/Message.cs
> +    {
buniyam

2023-06-22 11:05 UTC, mrIminjonov commented on TestHotel/EmailService/EmailConfiguration.cs
> +    }
ochirvor

2023-07-01 10:42 UTC, MirazamTUT approved these changes

2023-07-08 11:47 UTC, merged