added models
isfandiyoro5/HotelMS pull request #4
Opened 2023-04-17 18:00 UTC by Bekhzod7799

2023-04-18 19:03 UTC, MirazamTUT requested changes

2023-04-18 19:03 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/Role.cs
> +        public Employee Employee { get; set; }
employee listda bo'lishi kerak edi

2023-04-18 19:03 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/Employee.cs
> +        public List<Roles> Role { get; set; }
Role listda bo'lishi kerak emas edi

2023-04-18 19:03 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/RoomType.cs
> +        public string RoomImg { get; set; }
RoomImg ni RoomImages ga o'zgartirish kerak

2023-04-18 19:03 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/RoomType.cs
> +        public int RoomTypesID { get; set: }
RoomTypesID dan "s" ni olip tashlash kerak

2023-04-18 19:03 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/Room.cs
> +        public enum RoomTypesID { get; set; }
RoomTypesID dan "s"ni olish va enumni int qilish kerak edi

2023-04-18 19:03 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/Room.cs
> +        public int RoomTypes { get; set; }
RoomTypes ni enum qilish kerak

2023-04-18 19:03 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/Hotel.cs
> +        public int StarRating { get; set; }
manmcha buni keremas diyudila

2023-04-18 19:14 UTC, MirazamTUT requested changes

2023-04-18 19:14 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/RoomType.cs
> +        public int RoomPrice { get; set; }
int ni double qilish kerak masmidi?

2023-04-18 19:27 UTC, MirazamTUT requested changes

2023-04-18 19:27 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/Booking.cs
> +        public int BookingId { get; set; }
HotelID qo'shmabsiz diyagrammada bor ekan

2023-04-18 19:27 UTC, MirazamTUT commented on TestHotel/TestHotel.DataAccess/Model/Employee.cs
> +        public int EmployeeID { get; set; }
HotelID qopketibdi chunki diagrammada bor edi

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Booking.cs
> +        public int BookingId { get; set; }
Ok, HotelCode Hotel Id ga alishtirildi.

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Employee.cs
> +        public int EmployeeID { get; set; }
Ok, done.

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Employee.cs
> +        public List<Roles> Role { get; set; }
ok, done

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Role.cs
> +        public Employee Employee { get; set; }
ok, done

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Room.cs
> +        public int RoomTypes { get; set; }
ok, done

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Room.cs
> +        public enum RoomTypesID { get; set; }
ok done

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/RoomType.cs
> +        public string RoomImg { get; set; }
ok, done

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/RoomType.cs
> +        public int RoomPrice { get; set; }
ok, done

2023-04-19 05:55 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/RoomType.cs
> +        public int RoomTypesID { get; set: }
ok, done

2023-04-19 06:49 UTC, isfandiyoro5 requested changes

2023-04-19 06:49 UTC, isfandiyoro5 commented on TestHotel/TestHotel.DataAccess/Model/Hotel.cs
> +        public int NumberRooms { get; set; }
NumberOfRooms

2023-04-19 06:49 UTC, isfandiyoro5 commented on TestHotel/TestHotel.DataAccess/Model/Booking.cs
> +        //public string SpecialRequest { get; set; } (alohida table qilinadi)
bu request ochiriladi

2023-04-19 06:49 UTC, isfandiyoro5 commented on TestHotel/TestHotel.DataAccess/Model/Employee.cs
> +        public DateTime BirthdayDate { get; set; }
BirthDate bolishi kk

2023-04-19 11:44 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Hotel.cs
> +        public int NumberRooms { get; set; }
ok, done

2023-04-19 11:45 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Employee.cs
> +        public DateTime BirthdayDate { get; set; }
ok, done

2023-04-19 11:45 UTC, Bekhzod7799 commented on TestHotel/TestHotel.DataAccess/Model/Booking.cs
> +        //public string SpecialRequest { get; set; } (alohida table qilinadi)
ok, done

2023-04-22 10:13 UTC, isfandiyoro5 approved these changes

2023-04-22 10:15 UTC, MirazamTUT approved these changes

2023-04-22 10:16 UTC, merged