Added DtoModels
isfandiyoro5/HotelMS pull request #6
Opened 2023-04-22 16:54 UTC by isfandiyoro5

2023-04-22 18:15 UTC, SheraliErkayev requested changes

2023-04-22 18:15 UTC, SheraliErkayev commented on TestHotel/TestHotel.DataAccess/DTO/RequestDto/EmployeeRequestDto.cs
> +        public int Salary { get; set; }
Salary double bolishi kerak. Modelni ham o'zgartitirsh kerak shuni doublega

2023-04-22 18:15 UTC, SheraliErkayev commented on TestHotel/TestHotel.DataAccess/DTO/ResponseDto/EmployeeResponseDto.cs
> +        public int Salary { get; set; }
int Salary => double Salary

2023-04-22 18:15 UTC, SheraliErkayev commented on TestHotel/TestHotel.DataAccess/DTO/ResponseDto/GuestResponseDto.cs
> +    internal class GuestResponseDto
public qilish kerak hamma dtolarni

2023-04-22 18:15 UTC, SheraliErkayev commented on TestHotel/TestHotel.DataAccess/DTO/ResponseDto/RoomTypeResponseDto.cs
> +    internal class RoomTypeResponseDto
RoomType lar qanaqa boladigan boldi? RoomType enum bolishi kerakmasmidi? DTOda description ham bolishi kerak turi bilan birga. masalan single room, double room. Buni modeli o'zgartirish kerak birinchi

2023-04-23 09:16 UTC, isfandiyoro5 commented on TestHotel/TestHotel.DataAccess/DTO/RequestDto/EmployeeRequestDto.cs
> +        public int Salary { get; set; }
qilindi

2023-04-23 09:17 UTC, isfandiyoro5 commented on TestHotel/TestHotel.DataAccess/DTO/ResponseDto/EmployeeResponseDto.cs
> +        public int Salary { get; set; }
bajarildi

2023-04-23 09:17 UTC, isfandiyoro5 commented on TestHotel/TestHotel.DataAccess/DTO/ResponseDto/GuestResponseDto.cs
> +    internal class GuestResponseDto
korib chiqiladi

2023-04-23 09:17 UTC, isfandiyoro5 commented on TestHotel/TestHotel.DataAccess/DTO/ResponseDto/RoomTypeResponseDto.cs
> +    internal class RoomTypeResponseDto
bu ham qilindi

2023-04-23 17:46 UTC, MirazamTUT approved these changes

2023-04-23 17:46 UTC, Bekhzod7799 approved these changes

2023-04-23 17:51 UTC, SheraliErkayev approved these changes

2023-04-23 17:52 UTC, merged